// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdjreuitpjuklvxfbuqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkanJldWl0cGp1a2x2eGZidXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NjIzOTMsImV4cCI6MjA1NTUzODM5M30.nc0wLgsHb1hpr6pVIOgurq23hTzWSqSiiu9DVFOrRVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);